const API='https://empowerment-api.mikotembo129.workers.dev/api/data';
let token=sessionStorage.getItem('emp_admin_token')||'';
let me=null,data={groups:[],members:[]};

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(action=null,payload={},auth=false){
  const body=action?JSON.stringify({action,...payload}):null;
  const opts=action?{method:'POST',headers:{'Content-Type':'application/json'},body}: {};
  if(auth) opts.headers={...(opts.headers||{}),Authorization:`Bearer ${token}`};
  const r=await fetch(API,opts); const j=await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(j.error||`Request failed (${r.status})`); return j;
}
async function login(e){
  e.preventDefault(); const error=document.getElementById('loginError'); error.textContent='';
  try{
    const j=await api('adminLogin',{username:username.value.trim(),password:password.value});
    token=j.token; sessionStorage.setItem('emp_admin_token',token); me=j.user; sessionStorage.setItem('emp_admin_user',JSON.stringify(me));
    document.getElementById('login').classList.add('hidden'); document.getElementById('app').classList.remove('hidden');
    adminName.textContent=me.name||me.username; role.textContent=me.role==='primary'?'Primary Administrator':me.role;
    applyRoleUI();
    await load();
  }catch(err){error.textContent=err.message}
}
async function load(){const j=await api('adminData',{},true);data={groups:j.groups||[],members:j.members||[]};renderAll();loadUsers();loadAudit();}
function applyRoleUI(){const primary=me?.role==='primary';const usersNav=document.getElementById('usersNav');const auditNav=document.getElementById('auditNav');const newUser=document.getElementById('newUser');if(usersNav){usersNav.style.display=primary?'':'none';usersNav.disabled=!primary;}if(auditNav){auditNav.style.display=primary?'':'none';auditNav.disabled=!primary;}if(newUser){newUser.style.display=primary?'':'none';newUser.disabled=!primary;}if(!primary){const users=document.getElementById('users');const audit=document.getElementById('audit');if(users)users.classList.remove('active');if(audit)audit.classList.remove('active');const dash=document.getElementById('dashboard');if(dash)dash.classList.add('active');const dashNav=document.querySelector('[data-page=dashboard]');if(dashNav){document.querySelectorAll('.sidebar nav button').forEach(x=>x.classList.remove('active'));dashNav.classList.add('active');}const title=document.getElementById('pageTitle');if(title)title.textContent='Dashboard';}}
function renderAll(){totalGroups.textContent=data.groups.length;totalMembers.textContent=data.members.length;pending.textContent=data.groups.filter(g=>g.status==='pending').length;amount.textContent='K'+data.groups.reduce((a,g)=>a+Number(g.amount||0),0).toLocaleString();recent.innerHTML=data.groups.slice(-5).reverse().map(g=>`<div class="row"><b>${esc(g.groupNumber||g.id)}</b> ${esc(g.name)} — ${esc(g.area)}</div>`).join('')||'<p>No registrations.</p>';renderGroups();renderMembers();renderEmpowerment()}
function renderGroups(){const q=(groupSearch?.value||'').toLowerCase();groupRows.innerHTML=data.groups.filter(g=>[g.groupNumber,g.name,g.area,g.contact,g.category].join(' ').toLowerCase().includes(q)).map(g=>`<tr><td>${esc(g.groupNumber||'—')}</td><td>${esc(g.name)}</td><td>${esc(g.category)}</td><td>${esc(g.area)}</td><td>${esc(g.contact)}<br>${esc(g.phone)}</td><td>${data.members.filter(m=>m.groupId===g.id).length}</td><td><button class="action" onclick="editGroup('${g.id}')">Edit</button>${me?.role==='primary'?`<button class="action danger" onclick="removeRecord('adminDeleteGroup','${g.id}')">Delete</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">No records.</td></tr>'}
function renderMembers(){const q=(memberSearch?.value||'').toLowerCase();memberRows.innerHTML=data.members.filter(m=>{const g=data.groups.find(x=>x.id===m.groupId);return[m.identityNumber,m.name,m.nrc,g?.name,m.phone].join(' ').toLowerCase().includes(q)}).map(m=>{const g=data.groups.find(x=>x.id===m.groupId);return `<tr><td>${esc(m.identityNumber)}</td><td>${esc(m.name)}<br>${esc(m.nrc)}</td><td>${esc(g?.name||'Unknown')}</td><td>${esc(m.gender)}</td><td>${esc(m.age)}</td><td>${esc(m.phone)}</td><td>${esc(m.position)}</td><td><button class="action" onclick="editMember('${m.id}')">Edit</button>${me?.role==='primary'?`<button class="action danger" onclick="removeRecord('adminDeleteMember','${m.id}')">Delete</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="8">No records.</td></tr>'}
function renderEmpowerment(){empowermentList.innerHTML=data.groups.map(g=>`<div style="padding:10px 0;border-bottom:1px solid #eee"><b>${esc(g.name)}</b> — ${esc(g.empowermentType||'Not specified')} — K${Number(g.amount||0).toLocaleString()}<br><small>${esc(g.activity||'')}</small></div>`).join('')||'<p>No records.</p>'}
function editGroup(id){const g=data.groups.find(x=>x.id===id);openModal(`<h3>Edit Group</h3><form id="editGroupForm"><label>Group ID</label><input id="egid" value="${esc(g.groupNumber)}"><label>Name</label><input id="egname" value="${esc(g.name)}" required><label>Category</label><input id="egcat" value="${esc(g.category)}"><label>Area/Ward</label><input id="egarea" value="${esc(g.area)}"><label>Contact</label><input id="egcontact" value="${esc(g.contact)}"><label>Phone</label><input id="egphone" value="${esc(g.phone)}"><label>Empowerment Type</label><input id="egetype" value="${esc(g.empowermentType)}"><label>Amount</label><input id="egamount" type="number" value="${Number(g.amount||0)}"><label>Activity</label><input id="egactivity" value="${esc(g.activity)}"><label>Notes</label><input id="egnote" value="${esc(g.note)}"><br><button class="primary">Save Changes</button></form>`);editGroupForm.onsubmit=async e=>{e.preventDefault();await adminSave('adminSaveGroup',{group:{...g,groupNumber:egid.value,name:egname.value,category:egcat.value,area:egarea.value,contact:egcontact.value,phone:egphone.value,empowermentType:egetype.value,amount:Number(egamount.value||0),activity:egactivity.value,note:egnote.value}})}}
function editMember(id){const m=data.members.find(x=>x.id===id);openModal(`<h3>Edit Member</h3><form id="editMemberForm"><label>Identity Number</label><input id="emid" value="${esc(m.identityNumber)}" required><label>Full Name</label><input id="emname" value="${esc(m.name)}" required><label>NRC/ID</label><input id="emnrc" value="${esc(m.nrc)}"><label>Gender</label><input id="emgender" value="${esc(m.gender)}"><label>Age</label><input id="emage" type="number" value="${esc(m.age)}"><label>Phone</label><input id="emphone" value="${esc(m.phone)}"><label>Position</label><input id="emposition" value="${esc(m.position)}"><br><button class="primary">Save Changes</button></form>`);editMemberForm.onsubmit=async e=>{e.preventDefault();await adminSave('adminSaveMember',{member:{...m,identityNumber:emid.value,name:emname.value,nrc:emnrc.value,gender:emgender.value,age:emage.value,phone:emphone.value,position:emposition.value}})}}
async function adminSave(action,payload){try{await api(action,payload,true);closeModal();await load()}catch(e){alert(e.message)}}
async function removeRecord(action,id){if(!confirm('Delete this record?'))return;await adminSave(action,{id})}
async function loadUsers(){if(me?.role!=='primary')return;try{const j=await api('adminUsers',{},true);userRows.innerHTML=(j.users||[]).map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.name)}</td><td>${esc(u.role)}</td><td>${esc(u.active?'Active':'Disabled')}</td><td><button class="action" onclick="toggleUser('${u.id}',${!u.active})">${u.active?'Disable':'Enable'}</button></td></tr>`).join('')}catch(e){userRows.innerHTML='<tr><td colspan="5">Unable to load users.</td></tr>'}}
async function toggleUser(id,active){await adminSave('setUserStatus',{id,active});await loadUsers()}
function openUser(){openModal(`<h3>Create Secondary User</h3><form id="userForm"><label>Full Name</label><input id="un" required><label>Username</label><input id="uu" required><label>Temporary Password</label><input id="up" type="password" required minlength="8"><label>Role</label><select id="ur"><option value="data_officer">Data Officer</option><option value="viewer">Viewer</option></select><br><button class="primary">Create Account</button></form>`);userForm.onsubmit=async e=>{e.preventDefault();try{await api('createUser',{name:un.value,username:uu.value,password:up.value,role:ur.value},true);closeModal();await loadUsers()}catch(x){alert(x.message)}}}
async function loadAudit(){try{const j=await api('audit',{},true);auditRows.innerHTML=(j.rows||[]).map(x=>`<div style="padding:8px 0;border-bottom:1px solid #eee"><b>${esc(x.username)}</b> — ${esc(x.action)} — ${esc(x.created_at)}</div>`).join('')||'<p>No activity.</p>'}catch(e){}}
function openModal(html){modalContent.innerHTML=html;modal.classList.remove('hidden')}function closeModal(){modal.classList.add('hidden')}
document.getElementById('loginForm').onsubmit=login;closeModal;document.getElementById('closeModal').onclick=closeModal;document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('emp_admin_token');sessionStorage.removeItem('emp_admin_user');location.reload()};document.getElementById('newUser').onclick=openUser;
document.querySelectorAll('.sidebar nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(b.dataset.page).classList.add('active');document.getElementById('pageTitle').textContent=b.textContent;document.querySelectorAll('.sidebar nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
groupSearch.oninput=renderGroups;memberSearch.oninput=renderMembers;
exportGroups.onclick=()=>downloadCSV(data.groups,'groups');exportMembers.onclick=()=>downloadCSV(data.members,'members');
function downloadCSV(rows,type){const arr=rows.map(r=>type==='groups'?{GroupID:r.groupNumber,Group:r.name,Category:r.category,Area:r.area,Contact:r.contact,Phone:r.phone,Amount:r.amount,Activity:r.activity}:{Identity:r.identityNumber,Name:r.name,NRC:r.nrc,Group:data.groups.find(g=>g.id===r.groupId)?.name||'',Gender:r.gender,Age:r.age,Phone:r.phone,Position:r.position});const keys=Object.keys(arr[0]||{Data:''});const csv=[keys.join(','),...arr.map(x=>keys.map(k=>`"${String(x[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${type}.csv`;a.click()}
try{const saved=sessionStorage.getItem('emp_admin_user');if(saved){me=JSON.parse(saved);document.getElementById('login')?.classList.add('hidden');document.getElementById('app')?.classList.remove('hidden');document.getElementById('adminName').textContent=me.name||me.username;document.getElementById('role').textContent=me.role==='primary'?'Primary Administrator':me.role;applyRoleUI();}}catch(e){}

